// Transactions
export const TRANSACTION_DELETE = "TRANSACTION_DELETE";
export const TRANSACTION_ADD = "TRANSACTION_ADD";
export const TRANSACTION_FETCH = "TRANSACTION_FETCH";
export const TRANSACTION_EDIT = "TRANSACTION_EDIT";
export const TRANSACTION_SET_LOADING = "TRANSACTION_SET_LOADING";

// Users
export const USER_FETCH = "USER_FETCH";
export const USER_SET_LOADING = "USER_SET_LOADING";
